# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backup CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
#    - uses: actions/checkout@v2
#      with:
#        fetch-depth: 0

    - name: Sync
      uses: actions/checkout@v2
      with:
        ref: master
    - uses: ilkka/git-https-push-action@master
      with:
        remoteUrl: https://mwcBpMGFbf:af38880e7423beae5a5d352f557696f51692d6da@e.coding.net/lunashu/eslint-config-nc_ursa/eslint-config-nc_ursa.git
        skipHooks: false
